--------------------------------------------------------
--  File created - œroda-maja-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KLIENT
--------------------------------------------------------

  CREATE TABLE "C##PATRYK"."KLIENT" 
   (	"ID_KLIENT" NUMBER(*,0), 
	"IMIE" VARCHAR2(20 BYTE), 
	"NAZWISKO" VARCHAR2(32 BYTE), 
	"ADRES" VARCHAR2(128 BYTE), 
	"PESEL" VARCHAR2(11 BYTE), 
	"TELEFON" VARCHAR2(9 BYTE), 
	"LOGIN" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PATRYK.KLIENT
SET DEFINE OFF;
Insert into C##PATRYK.KLIENT (ID_KLIENT,IMIE,NAZWISKO,ADRES,PESEL,TELEFON,LOGIN) values ('2','N1','N2','N3','N4','N5','test');
Insert into C##PATRYK.KLIENT (ID_KLIENT,IMIE,NAZWISKO,ADRES,PESEL,TELEFON,LOGIN) values ('41','PRAC','PRAC','PRAC','PRAC','pRAC','brak');
Insert into C##PATRYK.KLIENT (ID_KLIENT,IMIE,NAZWISKO,ADRES,PESEL,TELEFON,LOGIN) values ('101','test2','test2','test','test','test','test2');
Insert into C##PATRYK.KLIENT (ID_KLIENT,IMIE,NAZWISKO,ADRES,PESEL,TELEFON,LOGIN) values ('61','Anna','Mogi³a','Kokosowa 22','12312312312','123123123','brak');
Insert into C##PATRYK.KLIENT (ID_KLIENT,IMIE,NAZWISKO,ADRES,PESEL,TELEFON,LOGIN) values ('81','Kamil','Rym','Jakaœ tam 12','111111111','22222222','brak');
Insert into C##PATRYK.KLIENT (ID_KLIENT,IMIE,NAZWISKO,ADRES,PESEL,TELEFON,LOGIN) values ('22','Adrian','Drzewo','Parkowa 22 Warszawa','1235785','123456789','testx');
Insert into C##PATRYK.KLIENT (ID_KLIENT,IMIE,NAZWISKO,ADRES,PESEL,TELEFON,LOGIN) values ('1','Patryk','ToJA','TUTAJ','12345678901','123456789','brakk');
Insert into C##PATRYK.KLIENT (ID_KLIENT,IMIE,NAZWISKO,ADRES,PESEL,TELEFON,LOGIN) values ('21','patryk','patryk','par','patryk','patryk','patryk');
--------------------------------------------------------
--  DDL for Index KLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PATRYK"."KLIENT_PK" ON "C##PATRYK"."KLIENT" ("ID_KLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger KLIENT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PATRYK"."KLIENT_TRG" 
BEFORE INSERT ON KLIENT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_KLIENT IS NULL THEN
      SELECT KLIENT_SEQ.NEXTVAL INTO :NEW.ID_KLIENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PATRYK"."KLIENT_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table KLIENT
--------------------------------------------------------

  ALTER TABLE "C##PATRYK"."KLIENT" MODIFY ("ID_KLIENT" NOT NULL ENABLE);
  ALTER TABLE "C##PATRYK"."KLIENT" ADD CONSTRAINT "KLIENT_PK" PRIMARY KEY ("ID_KLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
