--------------------------------------------------------
--  File created - œroda-maja-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LOTY
--------------------------------------------------------

  CREATE TABLE "C##PATRYK"."LOTY" 
   (	"ID_LOT" NUMBER(*,0), 
	"NUMER_LOTU" VARCHAR2(10 BYTE), 
	"ID_SAMOLOT" NUMBER(*,0), 
	"DOSTEPNE_MIEJSCA" NUMBER(*,0), 
	"STARTOWANIE" VARCHAR2(20 BYTE), 
	"LADOWANIE" VARCHAR2(20 BYTE), 
	"POWROT" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"Z" VARCHAR2(20 BYTE), 
	"DO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PATRYK.LOTY
SET DEFINE OFF;
Insert into C##PATRYK.LOTY (ID_LOT,NUMER_LOTU,ID_SAMOLOT,DOSTEPNE_MIEJSCA,STARTOWANIE,LADOWANIE,POWROT,STATUS,Z,DO) values ('2','0','1','30','2020/05/06 11:00:00','2020/05/06 12:00:00','2020/05/06 13:00:00','Dostêpny','KorsarzLOT','Krosno');
--------------------------------------------------------
--  DDL for Index LOTY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PATRYK"."LOTY_PK" ON "C##PATRYK"."LOTY" ("ID_LOT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger LOTY_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PATRYK"."LOTY_TRG" 
BEFORE INSERT ON LOTY 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_LOT IS NULL THEN
      SELECT LOTY_SEQ.NEXTVAL INTO :NEW.ID_LOT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PATRYK"."LOTY_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table LOTY
--------------------------------------------------------

  ALTER TABLE "C##PATRYK"."LOTY" MODIFY ("ID_LOT" NOT NULL ENABLE);
  ALTER TABLE "C##PATRYK"."LOTY" ADD CONSTRAINT "LOTY_PK" PRIMARY KEY ("ID_LOT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
