--------------------------------------------------------
--  File created - poniedzia³ek-maja-18-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table NUMERY_REZERWACJI
--------------------------------------------------------

  CREATE TABLE "C##PATRYK"."NUMERY_REZERWACJI" 
   (	"ID_NR_REZERWACJI" NUMBER(*,0), 
	"NUMER_REZERWACJI" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PATRYK.NUMERY_REZERWACJI
SET DEFINE OFF;
Insert into C##PATRYK.NUMERY_REZERWACJI (ID_NR_REZERWACJI,NUMER_REZERWACJI) values ('1','57');
--------------------------------------------------------
--  DDL for Index NUMERY_REZERWACJI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PATRYK"."NUMERY_REZERWACJI_PK" ON "C##PATRYK"."NUMERY_REZERWACJI" ("ID_NR_REZERWACJI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger NUMERY_REZERWACJI_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PATRYK"."NUMERY_REZERWACJI_TRG" 
BEFORE INSERT ON NUMERY_REZERWACJI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_NR_REZERWACJI IS NULL THEN
      SELECT NUMERY_REZERWACJI_SEQ.NEXTVAL INTO :NEW.ID_NR_REZERWACJI FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PATRYK"."NUMERY_REZERWACJI_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table NUMERY_REZERWACJI
--------------------------------------------------------

  ALTER TABLE "C##PATRYK"."NUMERY_REZERWACJI" MODIFY ("ID_NR_REZERWACJI" NOT NULL ENABLE);
  ALTER TABLE "C##PATRYK"."NUMERY_REZERWACJI" ADD CONSTRAINT "NUMERY_REZERWACJI_PK" PRIMARY KEY ("ID_NR_REZERWACJI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
