--------------------------------------------------------
--  File created - œroda-maja-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRACOWNICY_LOGOWANIE
--------------------------------------------------------

  CREATE TABLE "C##PATRYK"."PRACOWNICY_LOGOWANIE" 
   (	"ID_LPRACOWNIK" NUMBER(*,0), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"HASLO" VARCHAR2(32 BYTE), 
	"STANOWISKO" VARCHAR2(20 BYTE), 
	"ID_PRACOWNIK" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PATRYK.PRACOWNICY_LOGOWANIE
SET DEFINE OFF;
Insert into C##PATRYK.PRACOWNICY_LOGOWANIE (ID_LPRACOWNIK,LOGIN,HASLO,STANOWISKO,ID_PRACOWNIK) values ('1','prac1','prac1','Pracownik','0');
Insert into C##PATRYK.PRACOWNICY_LOGOWANIE (ID_LPRACOWNIK,LOGIN,HASLO,STANOWISKO,ID_PRACOWNIK) values ('2','koor1','koor1','Koordynator','0');
--------------------------------------------------------
--  DDL for Index PRACOWNICY_LOGOWANIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PATRYK"."PRACOWNICY_LOGOWANIE_PK" ON "C##PATRYK"."PRACOWNICY_LOGOWANIE" ("ID_LPRACOWNIK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRACOWNICY_LOGOWANIE
--------------------------------------------------------

  ALTER TABLE "C##PATRYK"."PRACOWNICY_LOGOWANIE" MODIFY ("ID_LPRACOWNIK" NOT NULL ENABLE);
  ALTER TABLE "C##PATRYK"."PRACOWNICY_LOGOWANIE" ADD CONSTRAINT "PRACOWNICY_LOGOWANIE_PK" PRIMARY KEY ("ID_LPRACOWNIK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
