--------------------------------------------------------
--  File created - œroda-maja-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "C##PATRYK"."REZERWACJE" 
   (	"ID_REZERWACJA" NUMBER(*,0), 
	"NUMER_LOTU" VARCHAR2(10 BYTE), 
	"NUMER_MIEJSCA" VARCHAR2(10 BYTE), 
	"ID_KLIENT" NVARCHAR2(11), 
	"NUMER_REZERWACJI" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##PATRYK.REZERWACJE
SET DEFINE OFF;
Insert into C##PATRYK.REZERWACJE (ID_REZERWACJA,NUMER_LOTU,NUMER_MIEJSCA,ID_KLIENT,NUMER_REZERWACJI) values ('1','444','10','patryk','5');
Insert into C##PATRYK.REZERWACJE (ID_REZERWACJA,NUMER_LOTU,NUMER_MIEJSCA,ID_KLIENT,NUMER_REZERWACJI) values ('2','444','5','patryk','5');
--------------------------------------------------------
--  DDL for Index REZERWACJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##PATRYK"."REZERWACJE_PK" ON "C##PATRYK"."REZERWACJE" ("ID_REZERWACJA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger REZERWACJE_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##PATRYK"."REZERWACJE_TRG" 
BEFORE INSERT ON REZERWACJE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_REZERWACJA IS NULL THEN
      SELECT REZERWACJE_SEQ.NEXTVAL INTO :NEW.ID_REZERWACJA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##PATRYK"."REZERWACJE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "C##PATRYK"."REZERWACJE" MODIFY ("ID_REZERWACJA" NOT NULL ENABLE);
  ALTER TABLE "C##PATRYK"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_PK" PRIMARY KEY ("ID_REZERWACJA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
